$ErrorActionPreference = "Stop"

$scriptPath = Split-Path -Parent $MyInvocation.MyCommand.Path
$projectPath = Split-Path -Parent $scriptPath
$resourcePath = Join-Path $projectPath "resources"
$outputPath = Join-Path $resourcePath "factory_patches.rc"
$patchPath = Join-Path $projectPath "factory_patches"

$lines = [System.Collections.Generic.List[string]]::new()
$lines.Add("// Generated by scripts/prepare_resources-win.ps1. Do not edit by hand.")
$lines.Add("")

$index = 1
Get-ChildItem -LiteralPath $patchPath -Filter "*.toml" | Sort-Object Name | ForEach-Object {
  $patchName = $_.Name.Replace("\", "\\").Replace('"', '\"')
  $lines.Add(("FACTORY_PATCH_{0:D3} TOML ""..\\factory_patches\\{1}""" -f $index, $patchName))
  $index += 1
}

$contents = ($lines -join "`r`n") + "`r`n"
if ((Test-Path -LiteralPath $outputPath) -and ((Get-Content -LiteralPath $outputPath -Raw) -eq $contents)) {
  exit 0
}

[System.IO.File]::WriteAllText($outputPath, $contents, [System.Text.Encoding]::ASCII)
