#!/usr/bin/python3

import glob
import os

scriptpath = os.path.dirname(os.path.realpath(__file__))
projectpath = os.path.abspath(os.path.join(scriptpath, os.pardir))
resourcepath = os.path.join(projectpath, "resources")

def write_if_changed(path, contents):
  try:
    with open(path, "r", newline="") as existing:
      if existing.read() == contents:
        return
  except FileNotFoundError:
    pass

  with open(path, "w", newline="") as output:
    output.write(contents)

def main():
  patch_paths = sorted(glob.glob(os.path.join(projectpath, "factory_patches", "*.toml")))
  lines = [
      "// Generated by scripts/prepare_resources-win.py. Do not edit by hand.",
      "",
  ]

  for index, patch_path in enumerate(patch_paths, start=1):
    patch_name = os.path.basename(patch_path).replace("\\", "\\\\").replace('"', '\\"')
    lines.append(f'FACTORY_PATCH_{index:03d} TOML "..\\\\factory_patches\\\\{patch_name}"')

  write_if_changed(os.path.join(resourcepath, "factory_patches.rc"), "\n".join(lines) + "\n")

if __name__ == '__main__':
  main()
